name: Staging Frontend CI

on:
  pull_request:
    branches:
      - staging

jobs:
  frontend-ci:
    name: Frontend CI
    runs-on: ubuntu-latest
    env:
      VITE_API_URL: ${{ vars.VITE_API_URL }}
      VITE_COGNITO_POOL_ID: ${{ vars.VITE_COGNITO_POOL_ID }}
      VITE_COGNITO_CLIENT_ID: ${{ vars.VITE_COGNITO_CLIENT_ID }}
      VITE_COGNITO_DOMAIN: ${{ vars.VITE_COGNITO_DOMAIN }}
      VITE_GOOGLE_MAPS_API_KEY: ${{ secrets.VITE_GOOGLE_MAPS_API_KEY }}
      VITE_IS_TESTING: ${{ vars.VITE_IS_TESTING }}
      VITE_ENABLE_FEATURE_FLAGS: ${{ vars.VITE_ENABLE_FEATURE_FLAGS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build frontend
        run: yarn build
